#!/bin/bash
# Volume up using $mod+F3

# #--- amixer (ALSA) ---# #
amixer sset Master 5%+;
# #--- pulseaudio ---# #
# pactl set-sink-volume 0 +5%
msg=$(amixer sget Master | grep '%' | awk '{print $4}')
notify-send -t 700 'Volume: '$msg
