#!/bin/bash
# Volume up using $mod+F3

# #--- amixer (ALSA) ---# #
amixer sset Master 5%+;
# #--- pulseaudio ---# #
# pactl set-sink-volume 0 +5%
msg=$(amixer sget Master | grep -o "\[[0-9]\+%\]" -m 1)
notify-send -t 700 'Volume: '$msg
