#!/bin/bash
# Volume down using $mod+F2

# #--- amixer (ALSA) ---# #
amixer sset Master 5%-;
msg=$(amixer sget Master | grep '%' | awk '{print $4}')
# #--- pulseaudio ---# #
# pactl set-sink-volume 0 -5%

notify-send -t 700 'Volume: '$msg 
