#!/usr/bin/env sh

# Toggle floating dropdown terminal in i3, or start if non-existing.
# $1 is	the script run in the terminal.
# All other args are terminal settings.
# Terminal names are in dropdown_* to allow easily setting i3 settings.

[ -z "$1" ] && exit

script=$1
shift
if xwininfo -tree -root | grep "dropdown_$script";
then
	echo "Window detected."
	i3 "[title=\"dropdown_$script\"] scratchpad show; [title=\"$script\"] move position center"
else
	echo "Window not detected... spawning."
	# i3 "exec --no-startup-id st -t dropdown_$script $@ -e $script"
	if test "$script" = "term";
	then
		echo "st"
		i3 "exec --no-startup-id st -t dropdown_$script"
	else 
		echo "ranger"
		i3 "exec --no-startup-id st -t dropdown_$script -e $script"
	fi
	# spawn it. Without sleep, it doesn't work.
	sleep 0.31 &&\
	i3 "[title=\"dropdown_$script\"] scratchpad show; [title=\"$script\"] move position center"
fi
