#!/bin/bash

if xwininfo -tree -root | grep "$1";
then
	echo "Window detected"
	i3 "[class=\"${1^}\"] scratchpad show; [class=\"${1^}\"] move position center"
else
	echo "Window not detected... spawning"
	"$1" &
fi
