#!/bin/sh

# Example for $XDG_CONFIG_HOME/sxiv/exec/key-handler
# Called by sxiv(1) after the external prefix key (C-x by default) is pressed.
# The next key combo is passed as its first argument. Passed via stdin are the
# images to act upon, one path per line: all marked images, if in thumbnail
# mode and at least one image has been marked, otherwise the current image.
# sxiv(1) blocks until this script terminates. It then checks which images
# have been modified and reloads them.

# The key combo argument has the following form: "[C-][M-][S-]KEY",
# where C/M/S indicate Ctrl/Meta(Alt)/Shift modifier states and KEY is the X
# keysym as listed in /usr/include/X11/keysymdef.h without the "XK_" prefix.

rotate() {
	degree="$1"
	tr '\n' '\0' | xargs -0 realpath | sort | uniq | while read file; do
		case "$(file -b -i "$file")" in
		image/jpeg*) jpegtran -rotate "$degree" -copy all -outfile "$file" "$file" ;;
		*)           mogrify  -rotate "$degree" "$file" ;;
		esac
	done
}

case "$1" in
"C-c")
	## Copy image to clipboard
	# To paste in the web browser, the image needs to be converted into png
	# first. 
	while IFS="`printf '\n\t'`" read file
	do
		FILE_EXTENSION="${file##*.}"
		FILE_EXTENSION_LOWER=$(echo ${FILE_EXTENSION} | tr '[:upper:]' '[:lower:]')
		# notify-send -t 3000 "$file" "$FILE_EXTENSION"
		if [ "$FILE_EXTENSION_LOWER" = "png" ]
		then
			xclip -selection clipboard -target image/png "$file"
		else
			# https://www.reddit.com/r/archlinux/comments/c63f41/copying_a_jpeg_image_from_the_command_line_and/
			notify-send -t 3000 "Converting image to PNG"
			convert "$file" png:- | xclip -selection clipboard -target image/png
		fi
		notify-send -t 3000 "[Image] $file" "in clipboard"
	done ;;
"C-x")
	## Select marked files in lf
	while IFS="`printf '\n\t'`" read file; do 
		lf -remote "send $id select $file" && \
			lf -remote "send $id toggle $file" && \
			lf -remote "send $id up"
	done ;;
# "C-x")      xclip -in -filter | tr '\n' ' ' | xclip -in -selection clipboard ;;
# "C-e")      while read file; do urxvt -bg "#444" -fg "#eee" -sl 0 -title "$file" -e sh -c "exiv2 pr -q -pa '$file' | less" & done ;;
# "C-g")      tr '\n' '\0' | xargs -0 gimp & ;;
# "C-r")      while read file; do rawtherapee "$file" & done ;;
# "C-comma")  rotate 270 ;;
# "C-period") rotate  90 ;;
# "C-slash")  rotate 180 ;;
esac

