#!/bin/bash

c=$(echo -e "yes\nno" | dmenu -p "Screen capture?")

if [ $c = 'yes' ]; then
	f=$(date '+%Y%m%d-%H%M%S.png')
	gm import -window root ~/Pictures/$f
	notify-send -t 2800 "Screen captured" "~/Pictures/$f"
else
	exit
fi
