#!/bin/sh
## Wallpaper
__init_wallpaper(){
    swww init
    sleep 0.1
    swww img $HOME/.config/currbg.jpg
}
#chbg &
## Keyboard input
waybar &
fcitx5 &
nm-applet &
bluetooth off &
dunst &
# swww init && sleep 0.1 && swww img $HOME/.config/currbg.jpg &
__init_wallpaper &
#picom &
#mpd && mpd-mpris &
# ibus-daemon -drx &
# sleep 3 && ibus engine xkb:us::eng &
# ibus-daemon -drx --panel /usr/lib/ibus/ibus-ui-gtk3 &
# pypr &
## Window Manager
# exec i3
# blocks &
# exec dwm
