#!/bin/bash
# #--- Basic ---# #
killall sxhkd
sxhkd &
bspc rule -r "*"
# Launch polybar
$HOME/.config/polybar/launch.sh unicorn &
# Start workspaces on the main monitor.
bspc monitor eDP1 -d 1 2 3 4 5 6 7 8 9 0
# Define border and colors
bspc config border_width 3
bspc config window_gap 3
bspc config top_padding -1
# bspc config bottom_padding 0
# #d79921 #fff44f
bspc config normal_border_color "#44475a"
bspc config active_border_color "#ff79c6"
bspc config focused_border_color "#bd93f9"
bspc config presel_feedback_color "#6272a4"
# bspc config normal_border_color 	"#333"
# bspc config active_border_color		"#b16286"
# bspc config focused_border_color 	"#d79921"
# bspc config presel_feedback_color	"#b8bb26"
bspc config urgent_border_color 	"#dd2727"
# Hovering cursor focuses a window
bspc config focus_follows_pointer true
bspc config pointer_modifier mod4

# #--- Rule ---# #
# https://www.reddit.com/r/bspwm/comments/gvbm7j/floating_window_rules_not_being_applied/fsnr2uw/
bspc rule -a dropdown_term state=floating sticky=on
bspc rule -a dropdown_lf state=floating sticky=on
bspc rule -a dropdown_note state=floating sticky=on rectangle=724x436+1184+633 # 1920x1080
bspc rule -a dropdown_news state=floating sticky=on
bspc rule -a dropdown_ncmpcpp state=floating sticky=on
# https://github.com/baskerville/bspwm/issues/291#issuecomment-385970132
# $HOME/.local/bin/spotify overrides this rule
# bspc rule -a Spotify state=floating sticky=on
bspc rule -a Dragon-drag-and-drop sticky=on layer=above
bspc rule -a Slack state=floating sticky=on center=on
bspc rule -a Signal state=floating sticky=on center=on
bspc rule -a TelegramDesktop state=floating sticky=on
bspc rule -a zoom state=floating
bspc rule -a Inkscape state=floating
bspc rule -a net-imagej-launcher-ClassLauncher state=floating  # fiji
bspc rule -a fiji-Main state=floating
bspc rule -a Pavucontrol state=floating desktop=0
bspc rule -a *:easyeffects state=floating desktop=0
bspc rule -a Blueman-manager state=floating
bspc rule -a kakaotalk.exe state=floating desktop=0
bspc rule -a *:*:"Page Unresponsive" state=floating  # Brave
bspc rule -a Thunderbird desktop=9
bspc rule -a Thunderbird:"Activity" state=floating
bspc rule -a napari state=floating
bspc rule -a Peek state=floating sticky=on layer=above

bspc rule -a Zotero desktop=8
