#!/bin/bash
# #--- Basic ---# #
killall sxhkd
sxhkd &
bspc rule -r "*"
# Launch polybar
$HOME/.config/polybar/launch.sh unicorn &
# Start workspaces on the main monitor.
bspc monitor eDP1 -d 1 2 3 4 5 6 7 8 9 0
# Define border and colors
bspc config border_width 3
bspc config window_gap 3
bspc config top_padding -1
# bspc config bottom_padding 0
bspc config normal_border_color 	"#333"
bspc config active_border_color		"#b16286"
bspc config focused_border_color 	"#d79921"
bspc config presel_feedback_color	"#b8bb26"
bspc config urgent_border_color 	"#dd2727"
# Hovering cursor focuses a window
bspc config focus_follows_pointer true
bspc config pointer_modifier mod4

# #--- Rule ---# #
# https://www.reddit.com/r/bspwm/comments/gvbm7j/floating_window_rules_not_being_applied/fsnr2uw/
bspc rule -a dropdown_term state=floating sticky=on
bspc rule -a dropdown_lf state=floating sticky=on
bspc rule -a dropdown_note state=floating sticky=on rectangle=724x436+1180+610 # 1920x1080
# https://github.com/baskerville/bspwm/issues/291#issuecomment-385970132
# $HOME/.local/bin/spotify overrides this rule
# bspc rule -a Spotify state=floating sticky=on
bspc rule -a Dragon-drag-and-drop sticky=on
bspc rule -a Slack state=floating sticky=on
bspc rule -a Signal state=floating sticky=on
bspc rule -a zoom state=floating
bspc rule -a Inkscape state=floating
bspc rule -a fiji-Main state=floating

bspc rule -a Zotero -o desktop=8
