#!/bin/sh
win_id=$(xdo id -N "$1")
cmd="$2"
geometry=${3:-"80x24"}
if [ -z "$win_id" ]; then
	columns=${geometry%%x*}
	lines=${geometry##*x}
	if [ -n "$cmd" ]; then
		# Last $cmd should be quoted to force argument splitting
		alacritty --class "Alacritty,$1" -o "window.dimensions.columns=$columns" "window.dimensions.lines=$lines" -e $cmd
	else
		alacritty --class "Alacritty,$1" -o "window.dimensions.columns=$columns" "window.dimensions.lines=$lines"
	fi
else
	bspc node $win_id -g hidden -f
fi
