#!/bin/sh
win_id=$(xdo id -N "$1")
geometry=${3:-"80x24"}
if [ -z "$win_id" ]; then
	if [ -n "$2" ]; then
		$TERMINAL -c "$1" -g "$geometry" -e "$2"&
	else
		$TERMINAL -c "$1" -g "$geometry" &
	fi
else
	bspc node $win_id -g hidden -f
fi
