#!/bin/bash

cap=$(cat /sys/class/power_supply/BAT0/capacity)
stat=$(cat /sys/class/power_supply/BAT0/status)

case $stat in
	Charging)
		est="$(acpi -b | grep -oP '\d{2}:\d{2}')"
		# echo "${cap}% ${est}"
		[ "$cap" -ge 100 ] && notify-send "🍙 Fully charged"
		# Lime #00ff00
		printf "%%{F#00ff00}%s%% %%{F-}%s" "$cap" "$est"
		;;
	Discharging)
		est="$(acpi -b | grep -oP '\d{2}:\d{2}')"
		if [ "${est%:*}" -lt 1 ]; then
			#ff0000 #fabd2f #ff0066
			printf "%%{F#ff0066}%s%% %%{F-}%s" "$cap" "$est"
			# [ "${est:3:5}" -lt 30 ] && notify-send -t 3000 "Plug in"
		else
			printf "%s%% %s" "$cap" "$est"
		fi
		;;
	FULL)
		echo "FULL"
		;;
	*)
		exit 2
		;;
esac

