#!/bin/sh
INTERVAL=${INTERVAL:-15}

while true
do
    if [ -n "$(pidof openvpn)" ]
    then
        printf "🦈\n"
    else
        printf "%%{F#ff4500}%s%%{F-}\n" "NoVPN"
    fi

    sleep $INTERVAL &
    wait
done
